const { PrismaClient } = require("@prisma/client")

const prisma = new PrismaClient()

const questions = [
  {
    question:
      "What insights regarding reaction pathways, intermediate products, and reactivity descriptors for electrochemical nitrate reduction to ammonia on Cu(100) and Cu(111) surfaces in alkaline media are provided by grand-canonical DFT calculations?",
    answer:
      "Grand-canonical DFT calculations provide free energy profiles for ammonia formation from nitrate reduction on Cu(100) and Cu(111) surfaces at 0 V vs. RHE, identifying the free formation energies of NO2\u207b(aq) and NH2OH(aq) as intermediate products along the reaction pathway. The calculations utilize adsorption energies of bridge-bidentate *NO3 and hollow *N as reactivity descriptors, which populate an activity volcano plot predicting that Cu(100) is more active than Cu(111). Additionally, the calculations reveal a linear scaling relation between *NO3 and *N adsorption energies with a slope of 1.19 for late transition metals, while noting that copper exhibits distinct scaling behavior due to repulsive interactions from its fully occupied d-band.",
    reasoning:
      "Question Mapping: The question seeks mechanistic insights from grand-canonical DFT calculations regarding electrochemical nitrate reduction to ammonia on Cu(100) and Cu(111) surfaces, specifically requesting information on: (i) reaction pathways, (ii) intermediate products, and (iii) reactivity descriptors used to predict activity trends.\n\nEvidence Mapping: blk_0156 provides the free energy profiles at 0 V vs. RHE, identifies NO2\u207b(aq) and NH2OH(aq) as intermediate products along the pathway, and specifies the use of bridge-bidentate *NO3 and hollow *N adsorption energies as reactivity descriptors for constructing the activity volcano plot. blk_0157 provides the predicted activity trend (Cu(100) > Cu(111)), the linear scaling relation between *NO3 and *N adsorption energies with slope 1.19 for late transition metals, and the distinct scaling behavior of copper arising from repulsive interactions due to its fully occupied d-band.\n\nAnswer Logic: The answer constructs a comprehensive mechanistic picture by: (1) establishing the thermodynamic reaction pathway via free energy profiles and identifiable aqueous intermediates, (2) quantifying catalytic activity through descriptor-based volcano plots using specific adsorption configurations, and (3) contextualizing copper\u2019s behavior within universal transition metal scaling relations while noting its unique electronic structure effects.",
    evidence:
      "In this work, we develop a mechanistic understanding of NO3RR on Cu surfaces in alkaline media with grand-canonical density functional theory (DFT) calculations. With the adsorption energies of bridge-bidentate *NO3 and hollow *N as reactivity descriptors, the volcano plot very well captures the known activity trends of pure metals. Free energy profiles of NH3 formation from NO3\u207b reduction on Cu(100) and Cu(111) at 0 V vs. RHE from grand-canonical DFT calculations identify the free formation energies of intermediate products NO2\u207b(aq) and NH2OH(aq). The activity volcano plot uses adsorption energies of bridge-bidentate *NO3 and hollow *N as reactivity descriptors. There is a strong linear scaling of adsorption energies between *NO3 and *N for late transition metals with a slope of 1.19 (R\u00b2: 0.88). Coinage metals (Cu, Ag, and Au) typically follow energy scaling with a different slope due to repulsive interactions from the fully occupied metal d-band.",
  },
  {
    question:
      "How do the adsorption energies of bridge-bidentate *NO3 and hollow *N serve as universal descriptors for constructing activity volcano plots and predicting nitrate reduction trends across late transition and noble metal (100) and (111) facets?",
    answer:
      "The adsorption energies of bridge-bidentate *NO3 and hollow *N serve as universal descriptors by establishing linear scaling relations with the free formation energies of nitrate reduction reaction intermediates across late transition and noble metal surfaces. These specific configurations\u2014*NO3 adsorbed at the bridge site and *N at the four-fold hollow site\u2014provide simple yet accurate measures for capturing the thermodynamic stability of intermediates on both (100) and (111) facets. By calculating these adsorption energies and plotting the theoretical activity (characterized by the highest free energy change at 0 V versus RHE) against these descriptor values, activity volcano plots are constructed that effectively capture and predict nitrate reduction trends across different metals, with distinct representations for (111) and (100) surface orientations.",
    reasoning:
      "Question Mapping: The question seeks the mechanistic rationale for using bridge-bidentate *NO3 and hollow *N adsorption energies as universal descriptors in nitrate reduction electrocatalysis. Key aspects include: (1) the specific adsorption configurations (bridge vs. hollow), (2) the establishment of linear scaling relations with reaction intermediates, (3) the construction methodology for activity volcano plots, and (4) the differentiation between (100) and (111) surface facets for late transition and noble metals.\n\nEvidence Mapping: blk_0017 provides the theoretical foundation, detailing the linear adsorption-energy scaling relations, the selection of *N at four-fold hollow and *NO3 at bridge sites for thermodynamic accuracy, and the use of highest free energy change at 0 V vs. RHE as the activity metric for both facet types. blk_0156 provides the graphical validation, confirming these descriptors generate volcano plots with distinct symbols for (111) (circles) and (100) (squares) surfaces.\n\nAnswer Logic: The adsorption energies serve as universal descriptors by establishing linear scaling relations with the free formation energies of all nitrate reduction intermediates. The specific choice of bridge-bidentate *NO3 and four-fold hollow *N configurations provides optimal simplicity while accurately capturing thermodynamic stability across metal surfaces.",
    evidence:
      "To understand the activity trends of NO3RR across elemental metals, we have calculated the free formation energies of reaction intermediates on the (100) and (111) facets of late transition and noble metals at the most stable configurations. Linear adsorption-energy scaling relations of reaction intermediates with *NO3 and *N as descriptor species were used to develop the activity volcano plot. The adsorption energies of *N at the four-fold hollow site and *NO3 at the bridge site were used because of the simplicity and accuracy for capturing the thermodynamic stability of reaction intermediates. We used the highest free energy change of all reaction steps at 0 V vs. RHE to characterize the theoretical activity of (100)- and (111)-like metal sites. Circle and square symbols represent (111) and (100) metal surfaces, respectively.",
  },
  {
    question:
      "How does the Bayeschem Bayesian model utilize projected density of states onto adsorbate frontier orbitals to predict chemisorption energies of *NO3 and *N intermediates on metal surfaces?",
    answer:
      "The Bayeschem Bayesian model utilizes projected density of states onto adsorbate frontier orbitals by employing localized Wannier functions projected onto the frontier orbitals of gas-phase NO3 and N radicals. Built upon d-band theory and the Newns-Anderson model Hamiltonian, the model learns from ab initio adsorption properties to predict chemisorption energies. For the *N intermediate, the model captures contributions from pxy and pz orbitals, identifying both bonding and antibonding states. For *NO3, the model accounts for the HOMO exhibiting antibonding states that pin across the Fermi level, while the LUMO remains too high in energy to be occupied, forming a Lorentzian-shaped resonance state. By analyzing these orbital-specific electronic structures and their interactions with surface electronic factors\u2014such as the d-band center and interatomic coupling strength\u2014the model predicts chemisorption energies and their response to electronic perturbations on both (100)- and (111)-terminated metal surfaces.",
    reasoning:
      "Question Mapping: The question seeks the mechanism by which the Bayeschem Bayesian model employs projected density of states (PDOS) onto adsorbate frontier orbitals to predict chemisorption energies for *NO3 and *N intermediates on metal surfaces. Key elements include the projection methodology (Wannier functions), theoretical framework (Newns-Anderson model Hamiltonian and d-band theory), orbital-specific electronic structures (pxy/pz for *N; HOMO/LUMO characteristics for *NO3), and the role of surface electronic factors (d-band center, interatomic coupling strength) across (100)- and (111)-terminated surfaces.\n\nEvidence Mapping: The evidence describes Bayeschem as an interpretable machine learning approach using Bayesian optimization trained on ab initio adsorption properties, built upon d-band theory and the Newns-Anderson model. It specifies the use of localized Wannier functions projected onto frontier orbitals of gas-phase NO3 and N radicals to generate PDOS. For *N, the model captures contributions from pxy and pz orbitals with identifiable bonding and antibonding states. For *NO3, the model accounts for HOMO antibonding states pinning across the Fermi level and an unoccupied LUMO forming a Lorentzian-shaped resonance state.\n\nAnswer Logic: The answer synthesizes the evidence by first establishing the technical projection method (localized Wannier functions on gas-phase radical frontier orbitals) and theoretical foundation (Newns-Anderson/d-band framework). It then details the distinct orbital analysis for each intermediate.",
    evidence:
      "Physical insights from interpretable ML. To pinpoint the physical origin of the linear scaling relations between *NO3 and *N adsorption energies on metal surfaces beyond the valency argument, we have employed a recently-developed Bayesian theory of chemisorption (Bayeschem) as an interpretable ML approach. Built upon the d-band theory of chemisorption and Bayesian optimization by learning from ab initio adsorption properties, Bayeschem has been used for qualitatively understanding the nature of chemical bonding and underlying electronic factors governing the trend of surface reactivity. DFT-calculated and model-predicted density of states projected onto adsorbate frontier orbitals, with Cu(100) as an example. For *N, both pxy and pz orbitals contribute to the adsorption energy with clearly captured bonding and antibonding states. In comparison, the HOMO of *NO3 has antibonding states pinning across the Fermi level, while the LUMO is too high in energy to be occupied, thus forming a Lorentzian-shaped resonance state. Localized Wannier functions projected onto the frontier orbitals of gas-phase NO3 and N radicals are shown.",
  },
  {
    question:
      "What electronic structure insights from interpretable machine learning explain the physical origin of linear scaling relations between *NO3 and *N adsorption energies on transition metal surfaces beyond simple valency arguments?",
    answer:
      "Interpretable machine learning based on the Bayesian theory of chemisorption (Bayeschem), which integrates the Newns-Anderson model Hamiltonian with d-band theory, reveals that the linear scaling between *NO3 and *N adsorption energies originates from their shared dependence on the d-band center of surface sites. When the d-band center shifts in response to electronic perturbations, the adsorption energies of both species change in parallel\u2014becoming more favorable with higher d-band centers and less favorable with lower ones\u2014regardless of surface termination. This relationship holds despite fundamentally different frontier orbital interactions: *N adsorption involves pxy and pz orbitals with distinct bonding and antibonding states, while *NO3 exhibits antibonding HOMO states pinned at the Fermi level and an unoccupied LUMO forming a Lorentzian-shaped resonance state. The model further elucidates that while increasing interatomic coupling strength initially strengthens *N adsorption through depopulation of antibonding states, Pauli repulsion dominates at high coupling values, introducing nonlinearities that can potentially break the scaling relation on specific surface geometries.",
    reasoning:
      "Question Mapping: The question seeks the physical origin of linear scaling between *NO3 and *N adsorption energies on transition metals, specifically requesting electronic structure insights derived from interpretable machine learning that go beyond simple valency arguments. Key components include: (1) identification of the interpretable ML framework used, (2) the shared electronic descriptor governing both adsorption energies, (3) reconciliation of this scaling with differing frontier orbital interactions, and (4) mechanisms that could potentially break these scaling relations.\n\nEvidence Mapping: blk_0158 provides the primary evidence, describing the Bayesian theory of chemisorption (Bayeschem) as the interpretable ML approach that integrates the Newns-Anderson model with d-band theory. It establishes that both adsorbates share dependence on the d-band center, shifting in parallel with electronic perturbations irrespective of surface termination.\n\nAnswer Logic: The answer synthesizes evidence to construct a mechanistic explanation: (1) It identifies Bayeschem as the interpretable ML framework connecting quantum mechanical models to reactivity trends; (2) It attributes linear scaling to the shared dependence of both adsorbates on the d-band center; (3) It explains that this scaling persists despite divergent orbital chemistries; (4) It incorporates the limitation that Pauli repulsion at high coupling strengths introduces nonlinearities.",
    evidence:
      "As the d-band center of surface sites shifts around in response to a perturbation, for example, by +1.5 to -1.5 eV, the adsorption energies of *NO3 and *N change side by side, i.e., a higher (lower) d-band center leads to a more (less) favorable interaction, irrespective of surface termination. Interestingly, with the increase of the interatomic coupling strength V\u00b2_ad, *N adsorption at the (100) hollow site becomes stronger first due to the depopulation of adsorbate-metal antibonding states but weakens as the change of V\u00b2_ad is larger than 4.0 eV\u00b2 where Pauli repulsion becomes dominant. This nonlinear correlation results from a complex interplay of the orbital hybridization and orthogonalization, both of which depend on the coupling strength V\u00b2_ad, albeit in different slopes. The Bayeschem model suggests that the (100)-facet of B2 structural motifs can potentially break adsorption-energy scaling relations.",
  },
  {
    question:
      "Why do (100)-terminated B2 intermetallic structures such as CuPd, ZnRh, and ZnCu break the linear adsorption-energy scaling relations observed between *NO3 and *N on pure Cu(100) surfaces?",
    answer:
      "(100)-terminated B2 intermetallics such as CuPd, ZnRh, and ZnCu break the linear adsorption-energy scaling relations because their bcc structural motif positions subsurface metal-ligands in close proximity to the hollow *N adsorption site. This geometric arrangement produces increased interatomic coupling that affects *N adsorption more drastically than *NO3 adsorption, enabling the simultaneous strengthening of *NO3 binding and weakening of *N binding compared to pure Cu(100) surfaces.",
    reasoning:
      "Question Mapping: The question seeks the structural and electronic origin of broken linear adsorption-energy scaling relations between *NO3 and *N on (100)-terminated B2 intermetallics (specifically CuPd, ZnRh, ZnCu) compared to pure Cu(100) surfaces.\n\nEvidence Mapping: blk_0334 establishes the mechanistic basis: B2 (bcc) intermetallic structures position subsurface metal-ligands in close proximity to hollow *N adsorption sites, generating increased interatomic coupling that differentially impacts *N adsorption relative to *NO3. blk_0335 validates the specific materials and adsorption trends: CuPd, ZnRh, and ZnCu exhibit non-scaling behavior characterized by stronger *NO3 adsorption and weaker *N adsorption compared to Cu(100).\n\nAnswer Logic: The bcc structural motif of B2 intermetallics creates a unique geometric arrangement where subsurface metal-ligands reside near the hollow *N adsorption site. This proximity produces enhanced interatomic coupling that affects *N binding more drastically than *NO3 binding, thereby decoupling their adsorption energies and breaking the linear scaling relations observed on pure Cu(100) surfaces.",
    evidence:
      "Structural analysis of 8 site motifs showed that the increase of interatomic coupling can be more drastic for the B2 (bcc) intermetallic structures because the subsurface metal-ligand is close to the hollow *N, as illustrated in Fig. 2e. Compared with Cu(100), (100)-terminated B2 CuPd, ZnRh, and ZnCu structures are predicted to exhibit reactivity properties beyond the scaling relations, i.e., a stronger *NO3 adsorption and a weaker *N adsorption. Zn-terminated ones are likely not stable in NO3RR operating conditions, and thus not considered for further studies. Cu-terminated CuPd (100) and (111) surfaces have been previously shown to be more stable than the Pd-termination using DFT-calculated surface energies.",
  },
  {
    question:
      "What high-temperature synthesis protocol enables the formation of monodisperse ordered B2 CuPd intermetallic nanocubes?",
    answer:
      "The protocol is a solution-phase synthesis involving consecutive decomposition and reduction of metal precursors. Specifically, copper(II) acetylacetonate, palladium(II) chloride, and 1,2-tetradecanediol are mixed in oleylamine and heated to 80\u00a0\u00b0C under nitrogen for 30 minutes. After injecting trioctylphosphine, the mixture is rapidly heated to 250\u00a0\u00b0C and maintained at this temperature for 30 minutes, where trioctylphosphine acts as a surfactant and oleylamine serves as both solvent and reductant. This high-temperature step enables the formation of monodisperse ordered B2 CuPd intermetallic nanocubes.",
    reasoning:
      "Question Mapping: The question seeks the specific high-temperature synthesis protocol used to create monodisperse ordered B2 CuPd intermetallic nanocubes, requiring identification of precursor chemicals, solvent system, temperature program, atmospheric conditions, and the functional roles of additives.\n\nEvidence Mapping: The evidence describes a solution-phase synthesis utilizing consecutive decomposition and reduction of metal precursors. It specifies the mixture of copper(II) acetylacetonate, palladium(II) chloride, and 1,2-tetradecanediol in oleylamine, initial heating to 80\u00a0\u00b0C under nitrogen, injection of trioctylphosphine, and subsequent rapid heating to 250\u00a0\u00b0C for 30 minutes. It defines oleylamine as both solvent and reductant and trioctylphosphine as a surfactant.\n\nAnswer Logic: The answer constructs the protocol by sequentially ordering the described procedural steps: precursor dissolution and initial heating, surfactant injection, and the critical high-temperature annealing step at 250\u00a0\u00b0C. It explicitly attributes the formation of the ordered B2 structure to this high-temperature step.",
    evidence:
      "We have synthesized well-defined ordered intermetallic CuPd nanocubes through the consecutive decomposition and reduction of corresponding metal precursors. Briefly, 0.1 mmol [Cu(acac)2] (acac = acetylacetonate), 0.1 mmol PdCl2 and 0.4 mmol 1,2-tetradecanediol (TDD) were mixed in 10 mL oleylamine (OAm), and heated under N2 atmosphere to 80\u00a0\u00b0C for 30 min. 0.5 mL trioctylphosphine (TOP) was injected into the solution. The mixture solution was then rapidly heated to 250\u00a0\u00b0C and maintained for 30 min. During the synthesis, TOP acts as the surfactant, while OAm acts as both the solvent and reductant. Representative SEM and TEM images of the as-synthesized sample reveal a uniform cubic morphology with a size of 50 \u00b1 4 nm.",
  },
  {
    question:
      "How does the onset potential for nitrate reduction on ordered CuPd nanocubes compare to pure Cu and Pd nanocubes in alkaline media, and what analytical techniques are used to quantify ammonia and nitrite production?",
    answer:
      "The ordered CuPd nanocubes exhibit an onset potential of 0.1 V vs. RHE for nitrate reduction, which is substantially more positive than that of pure Pd nanocubes (\u22120.05 V) and Cu nanocubes (\u22120.02 V) in alkaline media. Ion chromatography is employed to quantify nitrite production. For ammonia, the total production yield is determined by summing the amounts detected in the electrolyte and in a 0.1 M HCl trap placed at the outlet to capture volatilized products; however, the specific analytical technique used for the ammonia detection is not explicitly named in the provided evidence.",
    reasoning:
      "Question Mapping: The query requests (1) comparative onset potentials for nitrate reduction on ordered CuPd versus pure Cu and Pd nanocubes in alkaline media, and (2) analytical techniques for quantifying ammonia and nitrite products.\n\nEvidence Mapping: Electrochemical data provides onset potentials of 0.1 V vs. RHE for ordered CuPd, \u22120.05 V for Pd, and \u22120.02 V for Cu. Product analysis protocols specify ion chromatography for nitrite detection and describe ammonia quantification via summation of electrolyte and 0.1 M HCl trap contents, without identifying the specific detection method.\n\nAnswer Logic: The ordered CuPd catalyst exhibits a substantially more positive onset potential (0.1 V) compared to monometallic Pd (\u22120.05 V) and Cu (\u22120.02 V), indicating superior activity. Nitrite is quantified using ion chromatography. While the ammonia collection method (electrolyte plus acid trap) is detailed, the specific analytical technique for ammonia detection is not explicitly named in the evidence.",
    evidence:
      "The ordered CuPd nanocubes exhibit an onset potential of 0.1 V vs. RHE, which is much more positive than that of the Pd nanocubes (\u22120.05 V) and Cu nanocubes (\u22120.02 V). The partial current densities of NH3 on ordered CuPd nanocubes are much higher than that on Pd nanocubes and Cu nanocubes, suggesting that the ordered B2 CuPd nanocubes are much more active for the NO3RR toward NH3. The ordered CuPd nanocubes demonstrated high selectivity toward NH3 production from NO3RR with a FE of 92.5% at \u22120.5 V vs. RHE and a high yield rate of 6.25 mol h\u207b\u00b9 g\u207b\u00b9 at \u22120.6 V vs. RHE. Ion chromatography was employed to detect the quantity of produced NO2\u207b. To avoid the loss of products from continuous Ar flow, a glass vial filled with 0.1 M HCl was set at the end of the outlet tube as the trap. The total NH3 production yield was the summation of NH3 in the electrolyte and 0.1 M HCl.",
  },
]

async function main() {
  console.log("Seeding questions...")

  for (const q of questions) {
    await prisma.question.create({ data: q })
  }

  console.log(`Seeded ${questions.length} questions.`)
}

main()
  .catch((e) => {
    console.error(e)
    process.exit(1)
  })
  .finally(async () => {
    await prisma.$disconnect()
  })
